apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: default
spec:
  selector:
    app: hello
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
