apiVersion: v1
kind: Service
metadata:
  name: world-service
  namespace: default
spec:
  selector:
    app: world
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: NodePort
